[package]
name = "provable_vm"
version = "0.1.0"
edition = "2021"

[lib]
path = "src/lib.rs"

[dependencies]
bincode = "1.3.3"
eyre = "0.6.12"
hex = "0.4.3"
serde = { version = "1.0.217", features = ["derive"] }
sha2 = "0.10.8"
